### ISSUE TITLE
Tool does not record for borderless WPF window.

### ISSUE THREAD

**Issue by davideberly** [GameTechDev/PresentMon#121]
This is an excellent tool and has been very useful, thank you!

I have an application where I have WPF-DX11 interoperability. A shared surface is used for rendering. When the WPF window has default style (border, title bar and so on), the tool records information and writes to a specified CSV. When I change the window style (via XAML, WindowStyle="None" AllowsTransparency="True") to obtain a borderless window, the tool does not record any information. The spew from PresentMon for a bordered WPF window has several lines printed after the ** RECORDING** line. For the borderless WPF window, no lines are printed after the ** RECORDING** line, acting as if it does not detect the specified process. Any ideas how this can happen?

On a standard monitor and on a G-SYNC monitor, the CSV information for the bordered WPF window has "Composed: Copy with GPU GDI". My goal is to display the borderless WPF window of size 1920x1080 on a monitor whose native resolution is 1920x1080 and then see what present mode occurs.

If you decide to investigate, I can provide a zip file of the application to compile and run. All source code is included, no 3rd-party components. I use MSVS 2022 but can create projects instead for any of MSVS 2015/2017/2019.

Thank you.

**Comment by JeffersonMontgomery-Intel** [comment]
Sure, if you can provide the app I can take a look.

**Comment by davideberly** [comment]
Here is the [zip file](https://www.geometrictools.com/Temp/Experiments.zip). The top-level folder is named Experiments. It has a file ReadMe.txt that describes the steps I used to illustrate that PresentMon generates a CSV file for a bordered window but not for a borderless window. The window size does not matter, so I reduced it from 1920x1080 to 1280x720.

Thank you for taking the time to investigate!

**Comment by JeffersonMontgomery-Intel** [comment]
Thanks, I was able to reproduce this on my PC.  With bordered window I'm seeing D3D9 present events coming from a wpfgfx_cor3.dll thread in the WPFApplication.exe process, but with None/True I don't (nor any other present event).  So, PresentMon doesn't show anything because it doesn't see any initial present event to track.

It looks like the app is coordinating with DWM in some different way in this case (i.e., not presenting through a standard present api).  Unfortunately this won't be a quick fix, it will take some time to figure out how that's working and whether there is an event PresentMon can use to start tracking presents for this case or not.

**Comment by davideberly** [comment]
Thanks for looking. No worries about fixing it. I doubt many folks use WPF-DX11 interoperability, so I might very well be the only one encountering this. My goal was to understand what flip mode is used in borderless to convince a client not to use WPF (and its DX9 underpinnings).

The sample I provided uses D3DImage, which is a class Microsoft provided to obtain interoperability. The D3DImage source code is available online in case you decide to get PresentMon to handle the borderless case.
