### ISSUE TITLE
The FPS value is much larger at the moment exit one game.

### ISSUE THREAD

**Issue by feengg** [GameTechDev/PresentMon#133]
The fps values are very big when a exit the game 'Heaven.exe'
SyncInterval=0 Flags=0 CPU/Display=0.33/0.33ms (2994.3/2994.1 fps) latency =1.24ms Hardware: Ind

**Comment by JeffersonMontgomery-Intel** [comment]
Are you sure that this is wrong?  e.g., I could imagine a game presenting empty frames very fast as it exits.

If this is a PresentMon issue, I'll need an ETL that reproduces this in order to investigate (as described here: https://github.com/GameTechDev/PresentMon/blob/main/CONTRIBUTING.md#requesting-features-and-reporting-issues)

**Comment by jenatali** [comment]
Heaven specifically shows a credits screen after the main benchmark, which does in fact have a ridiculously high framerate.
