### ISSUE TITLE
Fighter Maker 2nd games are not having their FPS detected

### ISSUE THREAD

**Issue by Zero3K** [GameTechDev/PresentMon#138]
Fighter Maker 2nd games are not having their FPS detected. An example of such game can be found at https://mega.nz/file/JoJ0RaTY#cwVHOQbDDyrkpQlPNbDvkPwNsa3H0fYksx4ApNb9jQI.

**Comment by JeffersonMontgomery-Intel** [comment]
From what I can tell, it looks like this application is rendering by updating a GDI bitmap.

PresentMon doesn't support this technique, and can only track applications that use a more-recent graphics API such as OpenGL, DirectX, and Vulkan.  I'll update the readme to call this out, but otherwise I don't suspect we'll be able to support this application.

**Comment by Zero3K** [comment]
So, it is using DirectX only for the gamepad support?

**Comment by JeffersonMontgomery-Intel** [comment]
Yes, and audio.  But I don't see any other dx api calls nor related windows events getting created; and I don't see any other events that might be usable to measure this type of application.

**Comment by Zero3K** [comment]
Okay.
