### ISSUE TITLE
[FR] Signed builds compatible with AC solutions

### ISSUE THREAD

**Issue by Kein** [GameTechDev/PresentMon#144]
Tools like Reshade or Riva Tuner release signed builds with signatures that are whitelisted by many Anti-Cheat solutions so they can be used with the games that deploy such solutions. Are there any plans to do so for PM, considering new [recent] changes an direction?

**Comment by planetchili** [comment]
Currently we are signing the client application and the installer, and in the next release we will also have the service signed. Technically speaking, since we are not doing any injection/detouring for our overlay, we do not anticipate issues with AC. However, in the future we may explore allowing the user to select between different options for overlay mechanism (namely between injection/detouring and Multiplane Overlay). In such a scenario we would certainly reach out to the major players in the AC space to have our tool whitelisted.

**Comment by Kein** [comment]
Don't you hook up to the onPresent() for the stats and overlay? As far as I know all major AC solutions detect it as malicious activity within context of the process.

**Comment by JeffersonMontgomery-Intel** [comment]
Your right, but no: our overlay doesn't currently hook the app's present.

**Comment by Kein** [comment]
I'm not talking about just the overlay, but PM core as well. It does not hook `onPresent` at all?

**Comment by JeffersonMontgomery-Intel** [comment]
No.
