### ISSUE TITLE
Auto-target present mon overlay does not work with 3DMark must manually specify the process

### ISSUE THREAD

**Issue by tauheedul** [GameTechDev/PresentMon#151]
I tried testing PresentMon 0.5 while running the latest version of 3DMark 2.27.8160.

**_Overlay not displayed_**
With all the default options configured from out of the box experience, and the Preset **"GPU Focus"** selected
the overlay would not appear when running any 3D benchmark test.

I tried using the manual shortcut **"CTRL+SHIFT+O"** and this did not display the overlay while the test was running either.

The only way I could get it to work was to disable **Auto-target** process and manually select 3DMark Advanced Edition from the process list. 

This would then correctly display the overlay on top of the 3DMark application window and begin displaying statistics when any test is started.

**_Capture hotkey hides the overlay instead of logging_**
Also while the test was running and the statistics were being displayed I pressed **"CTRL+SHIFT+K"** to begin logging the statistics, but it instead hid the overlay. Pressing the shortcut again would unhide the overlay. I checked the **Capture Storage** file location and there were two csv files created. The file contained headers but no monitoring data.

My settings looked exactly like the example settings here
![presentmon settings](https://github.com/GameTechDev/PresentMon/assets/9335220/cec4b995-ee9b-437e-a95c-1998202454c5)

Image Source: https://www.techpowerup.com/img/ob1m3gOaRlDjJVZx.jpg

**Comment by planetchili** [comment]
Thank you for your feedback. The auto-targeting feature works by identifying processes that are utilizing GPU render resources and selecting the greatest utilization among them. Since it is unlikely that the 3D Mark benchmark configuration/launcher application is doing any 3D work itself, it is expected that auto-targeting will not work there. However, if you leave auto-targeting enabled and proceed to run the actual tests, the auto-targeting system should identify each test case is it runs and target it appropriately.

As for the capture hotkey hiding the overlay, this is also by design. In the detailed settings page for the overlay, there is an option to hide during capture, and this option is on by default. Therefore, the capture hotkey is working as expected, triggering a capture process to begin, and the start of the capture process is what triggers the overlay being hidden.
