### ISSUE TITLE
PresentMon 64 closes on launch

### ISSUE THREAD

**Issue by Rainy101** [GameTechDev/PresentMon#17]
when launch the cmd windows comes up and goes away does this every time i tried to use it already run it as admin and disable antivirus

**Comment by jdm3** [comment]
Are you running PresentMon64.exe from a command window, or just double-clicking it's icon from explorer or similar?  Currently, PresentMon requires command-line arguments to be passed to it (e.g., "PresentMon64.exe -captureall").

I will make a change so that running without arguments does something better than just print usage and exit.

**Comment by jdm3** [comment]
PresentMon64.exe can be run without command-line arguments as of v1.0.0 (https://github.com/GameTechDev/PresentMon/releases/tag/v1.0.0)
