### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by 1DanielKing** [GameTechDev/PresentMon#181]
![image](https://github.com/GameTechDev/PresentMon/assets/102125489/4cc83d6b-4101-4f22-97ab-af27433a9a67)

Hello, I am using Windows 10.0.19045.3570. I experienced PresentMon showing nearly 4 GB of RAM usage. I believe there may be a memory leak. I am not sure what other information to provide. Please let me know. I am a new dev.

**Comment by 1DanielKing** [comment]
I am not sure, I don't use it directly. It is related to my drivers or GPU software somehow. I am not very familiar with this application or project. But I made some updates to my system and it has not happened. Will let you know if it happens again and get that information for you as well. 
Thank you for reaching out.

**Comment by solemgar** [comment]
If someone else lands here, could please open a bug report with nvidia? I already opened one, but the more the better so we make sure it gets attention. Even nowadays, the PresentMon version they use is still 1.2.4923.0 and they haven't updated it since a long time. I still get really bad memory leak and reddit users keep reporting it too. 
https://www.nvidia.com/en-us/geforce/forums/notifications/topic/369090/
