### ISSUE TITLE
can't read CPU metrics after a crash

### ISSUE THREAD

**Issue by Susie1818** [GameTechDev/PresentMon#197]
Hi PresentMon Dev,

Could you tell me what PresentMon depends on to read CPU metrics? I just encountered a problem that after a game crash my PresentMon began to show CPU Name as "UNKNOWN_CPU" and CPU Utilization readout became "N/A%". I have tried uninstalling and reinstalling PresentMon but it still behaves like that. I think it is probably because the DLLs or some system files it depends on have been corrupted during the crash and I need to fix those files.

(I am using PresentMon 0.6 and it didn't have such a problem before the crash.)

**Comment by markgalvan-intel** [comment]
Hello! The CPU Name is obtained by creating a WQL query to retrieve it from Windows  Management Instrumentation (WMI). The CPU utilization is obtained by using the Windows Performance Counters. Since you are seeing "UNKNOWN_CPU" and "N/A%" it appears these calls are failing for some reason.

As a first test, when you have a free moment, can you please open up a PowerShell terminal and type in the following query (without the quotes):
"Get-WmiObject -Class Win32_Processor | Select-Object Name" 

This should return back the CPU Name like the following:

![wmi-ps-query](https://github.com/GameTechDev/PresentMon/assets/79164336/942edcc1-8363-46ad-90e9-9104b1c19342)

Please let us know the result of the query and we can proceed with next steps.

Thanks!

**Comment by markgalvan-intel** [comment]
Hello! Curious if this issue has been resolved? Please let us know.

**Comment by Susie1818** [comment]
Sorry but I have reinstalled my Windows so I actually didn't try to troubleshoot the problem.

**Comment by Susie1818** [comment]
I did use DISM and SFC commands to try to repair system files, but PresentMon still showed unknown CPU and n/a %. Therefore I just reinstalled my Windows.

**Comment by markgalvan-intel** [comment]
Thank you for responding! I'm glad to hear that PresentMon is now reporting back CPU information after the Windows install. Is it okay if we close down this issue?

**Comment by Susie1818** [comment]
Yes, this can be closed. It's a pity that I couldn't find the actual root cause of the problem and fix it.

**Comment by markgalvan-intel** [comment]
I'll close this issue for now. Should we encounter it again and find a solution, I'll update this issue with our findings.
