### ISSUE TITLE
How to choose a stable version, it's best not to have fatal problems like crashes

### ISSUE THREAD

**Issue by zhangmaofei** [GameTechDev/PresentMon#198]
When we were using version 1.9.2, we found a similar issue where non English named processes could not be recognized and caused crashes. After reviewing recent modification records, we found that the latest beta version has been updated, but the release has not been updated yet. We would like to know when the official 1.9.2 version plans to fix these bugs. Based on our requirements, we actually need a stable version to monitor the frame rate information of PC videos and games. Is there a more stable version than 1.9.2 that can be used in previous versions

**Comment by JeffersonMontgomery-Intel** [comment]
Yes, our normal model is to roll bug fixes into point releases (1.9.3 etc.) with a few larger releases per year.

This got disrupted recently because we are working on the next main release, but it keeps getting delayed for various reasons. 

I just created a [1.10.0 release](https://github.com/GameTechDev/PresentMon/releases/tag/v1.10.0) of the console application which should have all the latest fixes in it for you.  Hope that helps.
