### ISSUE TITLE
What do 1% percentile statistics mean in PresentMon

### ISSUE THREAD

**Issue by fuchaohan** [GameTechDev/PresentMon#219]
Doesn't FPS (1%)  mean 1% LOW in PresentMon?
![image](https://github.com/GameTechDev/PresentMon/assets/23447902/48ab6502-9374-4dad-9f62-f4acb18a8baf)

**Comment by RodroG-85** [comment]
The problem is they show an FPS value for that metric, but their "X%" percentile refers to (frame)times, not FPS. This way can be a bit misleading or confusing, as with a correct formulation, the 99th percentile of frametimes (99% of the values are lower) corresponds to the 1st percentile of FPS (99% of the values are higher), and the 1st percentile of (frame)times (1% of the values are lower) corresponds to the 99th percentile of FPS (1% of the values are higher).

Taxxor, one of the CapFrameX developers, covered this topic and explained this issue very well in the following article:

[Explanation of Different Performance Metrics](https://www.capframex.com/blog/post/Explanation%20of%20different%20performance%20metrics)

**Comment by JeffersonMontgomery-Intel** [comment]
Note also that we changed how this is handled from beta to 2.0.0 version.

Pre 2.0 we would invert the %ile statistic for metrics where "larger was better", but it's not always clear when or when not to do that, and in general converting automatically turned out to be more confusing than helpful.

In 2.0.0, the percentile statistic is not "context-aware".  1%ile will show the value where 1% of samples are less than or equal to that value, no matter what the set of values represent.  So 1%tile FPS will be the slower frames, but 1%ile frametime will be the faster frames.

**Comment by RodroG-85** [comment]
@JeffersonMontgomery-Intel  The formulation issue still stands in 2.0.0.

With a correct formulation, if you show a Presented FPS metric, you should display the Xth percentile of FPS, not the Xth percentile of (frame)times, as the unit of the shown metric is FPS, not (frame)times.

So, your Presented FPS (1%) metric should result in and show the 1st percentile of FPS or P1 FPS (99% of samples are higher than the displayed FPS value, and 1% of samples are less than or equal to such displayed FPS value). Accordingly, your Present FPS (99%) metric should result in and show the 99th percentile of FPS or P99 FPS (1% of samples are higher than such FPS value, and 99% of samples are lower than or equal to such FPS value).

**Comment by WeetA34** [comment]
> Note also that we changed how this is handled from beta to 2.0.0 version.
> 
> Pre 2.0 we would invert the %ile statistic for metrics where "larger was better", but it's not always clear when or when not to do that, and in general converting automatically turned out to be more confusing than helpful.
> 
> In 2.0.0, the percentile statistic is not "context-aware". 1%ile will show the value where 1% of samples are less than or equal to that value, no matter what the set of values represent. So 1%tile FPS will be the slower frames, but 1%ile frametime will be the faster frames.

Hello,
I'm using PresentMon 2.0.0, Presented FPS (99%) seems to still represent the 1% slower FPS. If i use Presented FPS (1%), i got higher values than average

**Comment by markgalvan-intel** [comment]
Consolidating this issue with https://github.com/GameTechDev/PresentMon/issues/238.
