### ISSUE TITLE
When Arc Control recording is on, 99% FPS is abnormally low

### ISSUE THREAD

**Issue by fuchaohan** [GameTechDev/PresentMon#239]
![image](https://github.com/GameTechDev/PresentMon/assets/23447902/dde82997-ba71-4451-be8d-c5f35c817027)
Present Runtime will suddenly become Unknown.
![image](https://github.com/GameTechDev/PresentMon/assets/23447902/0ed98a20-3753-480d-be1f-7ebfb918ff57)

**Comment by planetchili** [comment]
Thank you for reporting your issue. We attempted reproduction on our end with an Arc A750 and did not see the same performance degradation. We have decided not to pursue this issue because it affects a use case that is not our primary concern at the moment. Typically in scenarios where measurement accuracy is critical, it is recommended to avoid resource consuming side tasks such as screen capture or even overlay.
