### ISSUE TITLE
Memory Usage is too high

### ISSUE THREAD

**Issue by Zero3K** [GameTechDev/PresentMon#58]
I am using a debug build built for x64 architecture OSes that was made with the latest source code. It is using between 60-70 MB of RAM when it should be using 20-30 MB of RAM.

**Comment by JeffersonMontgomery-Intel** [comment]
I ran the Debug|x64 build of the latest version for a several minute capture.  Process memory did not exceed 8MB.

**Comment by spencero91** [comment]
I didn't install this service, so it's clearly being included with other programs under the hood. But I've closed most of the applications running on my system and it's still open and holding onto 2,483.3 MB. Seems a bit excessive for a monitoring tool. Not sure if this is something that's a problem with the vanilla package or a modified version from whatever installed it on my system.

**Comment by dstaley** [comment]
For anyone else who stumbles upon this: PresentMon is included in NVIDIA's FrameView SDK. If you're experiencing high memory usage, I'd try uninstalling FrameView. Unfortunately, it looks like Geforce Experience automatically installs it again, so you may have to do this every time you update your driver.

**Comment by rthomp10** [comment]
Does 35GB seem a little excessive? Running TeamViewer and a mining application, but haven't found the source of the issue. Any way I could forcefully make PresentMon use excessive memory
![Screen Shot 2022-01-11 at 1 01 34 PM](https://user-images.githubusercontent.com/21367652/149005168-4b2001b7-483c-4afb-ba21-828ecdc36d53.png)
?

**Comment by JeffersonMontgomery-Intel** [comment]
@rthomp10  Are you also running PresentMon through some other tool like FrameView?

It's a little hard for me to speculate how PresentMon is being used in that case, or what the interaction is causing this... but I'd guess: older versions of PresentMon continually collect information, and it's the parent tool's responsibility to handle the collected data.  If the parent tool leaves PresentMon running but doesn't remove the collected data, PresentMon will just keep collecting into a growing memory pool.

Newer versions of PresentMon use a fixed memory size, so instead of growing memory in the above case, older information is discarded as that fixed size overflows.

To answer your question about forcing this condition (assuming my above guess is correct) you'd need to get an older version of PresentMon, and you'd need to modify the PresentMon.exe source to not remove collected information.

**Comment by rthomp10** [comment]
Awesome, this is some extremely valuable information. I’m not at my computer right now, but I’m using an up-to-date Nvidia Driver that’s probably responsible.

___
Ryan Thompson

**Comment by m4heshd** [comment]
Currently using 22GB of committed memory. This application is single-handedly destroying my system drive NVMe. It's being used by some NVIDIA service (probably the NVIDIA performance overlay). How do I get rid of this issue without getting rid of the overlay? 

![image](https://github.com/GameTechDev/PresentMon/assets/6711514/d20db44b-0027-47f4-9273-7979f32b1403)

**Comment by Digit-89** [comment]
This is an URGENT issue - taking 80% of my memory as well, what the hell :(

**Comment by Zero3K** [comment]
It's not taking as much for me. But it could still be improved.

**Comment by JeffersonMontgomery-Intel** [comment]
Please contact NVIDIA support for help unless you are seeing this with an official version: https://github.com/GameTechDev/PresentMon/releases
