### ISSUE TITLE
Input lag parameter

### ISSUE THREAD

**Issue by DevTechProfile** [GameTechDev/PresentMon#60]
I'v got just a question. I hope it's ok. What parameter/column header represents the input lag (the delay between pressing a button and seeing the game react)?

**Comment by JeffersonMontgomery-Intel** [comment]
PresentMon doesn't directly measure the latency from user input to display, because it doesn't track input and can't know what the application uses or when it simulates its virtual world.

As a proxy for this, I use the time from the last frame's Present() call until this frame is displayed: MsBetweenPresents - previous MsInPresentAPI + MSUntilDisplayed.  This assumes that the application starts working on the frame right after presenting the previous frame, and it latches input/simulation time at that point.

Note that this is different form the latency displayed in the console output.  The console "latency" is showing just MsUntilDisplayed (i.e., the time between calling Present() and showing up on screen).

**Comment by DevTechProfile** [comment]
Many thanks.
